routes/web.php
<?php

use App\Http\Livewire\Account\Accsettings;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Fortify;
use Laravel\Fortify\Actions\EnableTwoFactorAuthentication;
use App\Models\DiscordVerification;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* AUTHENTICATION */

Route::get('/login', App\Http\Livewire\Login::class)->name('login');
Route::get('/register', App\Http\Livewire\Register::class)->name('register');

Route::get('/test', [App\Http\Controllers\LoginAuthenticationController::class, 'authenticate']);
Route::get('/verifydiscord', [App\Http\Controllers\DiscordVerificationController::class, 'index']);
Route::get('/discorddata', [App\Http\Controllers\DiscordVerificationController::class, 'getdata']);

//Fortify::verifyEmailView(function () {
//    return view('auth.verify-email');
//});

Route::get('/discord', function()
{
    $count = DiscordVerification::all()->count();
    return view('impact.discord')->with([
        'count' => $count
    ]);
})->name('discord-impact');

Route::get('/verify/{id}', App\Http\Livewire\Verify::class);
Route::get('/checkid/{id}', function($id)
{

    if(DiscordVerification::where('discord_id', $id)->get()->count() == 1) {
        $obj = (object) [
            'found' => true,
            'token' => DiscordVerification::where('discord_id', $id)->first()->token
        ];
    } else {
        $obj = (object) [
            'found' => false,
            'result' => DiscordVerification::where('discord_id', $id)->get()->count()
        ];
    }
    

    return json_encode($obj);
});


/* IMPACT */
Route::domain(env('APP_URL'))->group(function ()
{
    Route::get('/', App\Http\Livewire\Frontpage::class)->name('frontpage-impact');
    Route::get('/home', App\Http\Livewire\Dashboard\Dashboard::class)->name('home-impact');
    Route::get('/account/settings', App\Http\Livewire\Account\Accsettings::class)->middleware('auth');
    Route::get('/space/infrastructure', App\Http\Livewire\SpaceIS::class)->name('space');
    Route::get('/deploy', [App\Http\Controllers\DeployController::class, 'deploy']);
});

Route::domain('downloads.' . env('APP_URL'))->group(function ()
{
    Route::get('/', App\Http\Livewire\Downloads::class)->name('downloads');
});

Route::domain('raptor.' . env('APP_URL'))->group(function ()
{
    Route::get('/', App\Http\Livewire\Raptor::class)->name('raptor');
});


/* ADMIN PANEL */
Route::domain('admin.' . env('APP_URL'))->group(function ()
{
    Route::get('/', function () {
        return 'admin route';
    });
});

app/Http/Livewire/Account/.php
<?php

namespace App\Http\Livewire\Account;

use Livewire\Component;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\ImagickImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Laravel\Fortify\TwoFactorAuthenticationProvider;
use Laravel\Fortify\Actions\DisableTwoFactorAuthentication;
use Laravel\Fortify\Actions\EnableTwoFactorAuthentication;
use Auth;

class Security extends Component
{

    public function submit(Request $request, EnableTwoFactorAuthentication $two_enable, DisableTwoFactorAuthentication $two_disable, $enable) {
        if($enable == true) {
            $two_disable($request->user());
        } else {
            $two_enable($request->user());
        }
    }

    public function render(Request $request)
    {

        if(Auth::user()->two_factor_secret) {
            $renderer = new ImageRenderer(
                new RendererStyle(400),
                new ImagickImageBackEnd()
            );
            $writer = new Writer($renderer);
            $image = base64_encode($writer->writeString(app(TwoFactorAuthenticationProvider::class)->qrCodeUrl(
                config('app.name'),
                $request->user()->email,
                decrypt($request->user()->two_factor_secret)
            )));
        } else {
            $image = '';
        }
        

        return view('impact.account.components.security', ['render' => $image]);
    }
}

app/Http/Livewire/Account/AboutImpact.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class About extends Component
{
    public function render()
    {
        return view('livewire.about');
    }
}

app/Http/Livewire/Account/Accsettings.php
<?php

namespace App\Http\Livewire\Account;

use Livewire\Component;
use Auth;

class Accsettings extends Component
{
    public $active;

    public function mount() {
        $this->active = 'general';
    }

    public function render()
    {
        return view('impact.account.accsettings');
    }

    public function setPage($page) {
        $this->active = $page;
    }
}

app/Http/Livewire/Account/Advancedsettings.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Advancedsettings extends Component
{
    public function render()
    {
        return view('livewire.advancedsettings');
    }
}

app/Http/Livewire/Account/Connectedevices.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Connectedevices extends Component
{
    public function render()
    {
        return view('livewire.connectedevices');
    }
}

app/Http/Livewire/Account/Connections.php
<?php

namespace App\Http\Livewire\Account;

use Livewire\Component;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\ImagickImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Laravel\Fortify\TwoFactorAuthenticationProvider;
use Laravel\Fortify\Actions\DisableTwoFactorAuthentication;
use Laravel\Fortify\Actions\EnableTwoFactorAuthentication;
use Auth;
use App\Models\DiscordConnection;

class Connections extends Component
{
    public $discord_connection;

    public function render(Request $request)
    {

        $this->discord_connection = DiscordConnection::where('oaccount', Auth::user()->id)->get()->first();

        return view('impact.account.components.connections');
    }

    public function destroydc() 
    {
        DiscordConnection::where('oaccount', Auth::user()->id)->delete();
        $this->discord_connection = null;
    }
}

app/Http/Livewire/Account/General.php
<?php

namespace App\Http\Livewire\Account;

use Livewire\Component;
use Auth;

class General extends Component
{
    public $name;
    public $tag;
    public $email;
    public $fav_trail;
    public $fav_vehicle;

    public $status;

    public function updateprofileinformation()
    {
        $user = Auth::user();
        $user->name = $this->name;
        $user->tag = $this->tag;
        $user->fav_trail = $this->fav_trail;
        $user->fav_vehicle = $this->fav_vehicle;

        if($this->email != $user->email) {
            $user->email_verified_at = null;
            $user->email = $this->email;
        }

        $user->save();

        $this->status = 'success';
    }

    public function mount()
    {
        $this->name = Auth::user()->name;
        $this->tag = Auth::user()->tag;
        $this->email = Auth::user()->email;
        $this->fav_trail = Auth::user()->fav_trail;
        $this->fav_vehicle = Auth::user()->fav_vehicle;
    }

    public function render()
    {
        return view('impact.account.components.general', ['status' => $this->status]);
    }
}

app/Http/Livewire/Account/Paymentmethods.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Paymentmethods extends Component
{
    public function render()
    {
        return view('livewire.paymentmethods');
    }
}

app/Http/Livewire/Account/Privacy.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Privacy extends Component
{
    public function render()
    {
        return view('livewire.privacy');
    }
}

app/Http/Livewire/Account/Profilepicture.php
<?php

namespace App\Http\Livewire\Account;

use Livewire\Component;
use App\Models\DiscordConnection;
use Auth;
use League\OAuth2\Client\Provider\Discord;

class Profilepicture extends Component
{
    public $avatar;
    public $status;
    public $discord_connection;

    public function add_discord()
    {
        $user = Auth::user();
        $user->avatar_url = 'discord';
        $this->discord_connection = DiscordConnection::where('oaccount', Auth::user()->id)->first();
        $user->save();
    }

    public function remove_discord()
    {
        $user = Auth::user();
        $user->avatar_url = null;
        $this->discord_connection = DiscordConnection::where('oaccount', Auth::user()->id)->first();
        $user->save();
    }

    public function mount()
    {
        $this->discord_connection = DiscordConnection::where('oaccount', Auth::user()->id)->first();
        $this->name = Auth::user()->name;
        $this->avatar = Auth::user()->avatar_url;
    }

    public function render()
    {
        return view('impact.account.components.profilepicture', ['status' => $this->status]);
    }
}

app/Http/Livewire/Account/Security.php
<?php

namespace App\Http\Livewire\Account;

use Livewire\Component;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\ImagickImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Laravel\Fortify\TwoFactorAuthenticationProvider;
use Laravel\Fortify\Actions\DisableTwoFactorAuthentication;
use Laravel\Fortify\Actions\EnableTwoFactorAuthentication;
use Auth;

class Security extends Component
{

    public function submit(Request $request, EnableTwoFactorAuthentication $two_enable, DisableTwoFactorAuthentication $two_disable, $enable) {
        if($enable == true) {
            $two_disable($request->user());
        } else {
            $two_enable($request->user());
        }
    }

    public function render(Request $request)
    {

        if(Auth::user()->two_factor_secret) {
            $renderer = new ImageRenderer(
                new RendererStyle(400),
                new ImagickImageBackEnd()
            );
            $writer = new Writer($renderer);
            $image = base64_encode($writer->writeString(app(TwoFactorAuthenticationProvider::class)->qrCodeUrl(
                config('app.name'),
                $request->user()->email,
                decrypt($request->user()->two_factor_secret)
            )));
        } else {
            $image = '';
        }
        

        return view('impact.account.components.security', ['render' => $image]);
    }
}

app/Http/Livewire/Account/Securitypassword.php
<?php

namespace App\Http\Livewire\Account;

use Livewire\Component;
use Auth;
use Hash;

class Securitypassword extends Component
{
    public $oldpassword;
    public $newpassword;
    public $confirmpassword;
    public $status;

    public function render()
    {
        return view('impact.account.components.security-pass');
    }

    public function updatepassword() 
    {
        if($this->newpassword == $this->confirmpassword)
        {
            $hashedPassword = Auth::user()->password;
            if (\Hash::check($this->oldpassword , $hashedPassword )) {
                if (!\Hash::check($this->newpassword , $hashedPassword)) {
                    $user = Auth::user();
                    $user->password = Hash::make($this->newpassword);
                    $user->save();
                    $this->status = "success";
                } else {
                    $this->status = "fail";
                }
            } else {
                $this->status = "fail";
            }

            return null;
        } else {
            $this->status = "fail";
        }
    }
}

app/Http/Livewire/Dashboard/Components/Events.php
<?php

namespace App\Http\Livewire\Dashboard\Components;

use Livewire\Component;

class Events extends Component
{
    public function render()
    {
        return view('impact.dashboard.components.events');
    }
}

app/Http/Livewire/Dashboard/Components/Home.php
<?php

namespace App\Http\Livewire\Dashboard\Components;

use Livewire\Component;

class Home extends Component
{
    public function render()
    {
        return view('impact.dashboard.components.home');
    }
}

app/Http/Livewire/Dashboard/Components/Rides.php
<?php

namespace App\Http\Livewire\Dashboard\Components;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Ride;
use Auth;
use DB;

class Rides extends Component
{
    use WithPagination;

    public $ride_name;
    public $only_public = false;
    //public $rides;
    public $currentPage = 1;

    public $newride_name;
    public $newride_type;
    public $newride_location;
    public $newride_trail;
    public $newride_distance;

    public function render()
    {
        $ride_name = '%' . $this->ride_name . '%';

        $rides = Ride::where('name', 'LIKE', $ride_name)->where('oid', Auth::user()->id)->paginate(3);

        return view('impact.dashboard.components.rides', [
            'rides' => $rides
        ]);
    }

    public function newride()
    {
        $ride_component = new Ride;
        $ride_component->oid = Auth::user()->id;
        $ride_component->name = $this->newride_name;
        $ride_component->ridetype = $this->newride_type;
        $ride_component->location = $this->newride_location;
        $ride_component->trail = $this->newride_trail;
        $ride_component->distance = $this->newride_distance;
        $ride_component->save();
        return redirect('/dashboard');
    }
}

app/Http/Livewire/Dashboard/Components/Vehicles.php
<?php

namespace App\Http\Livewire\Dashboard\Components;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Vehicle;
use Auth;

class Vehicles extends Component
{
    use WithPagination;

    public $v_name;

    public $newveh_name;
    public $newveh_model;
    public $newveh_type;
    public $newveh_distance;
    public $newveh_alert;

    public function render()
    {
        $v_name = '%' . $this->v_name . '%';
        $vehicles = Vehicle::where('vehicle_name', 'LIKE', $v_name)->where('oid', Auth::user()->id)->paginate(15);

        return view('impact.dashboard.components.vehicles', [
            'vehicles' => $vehicles
        ]);
    }

    public function newveh() {
        $veh_component = new Vehicle;
        $veh_component->oid = Auth::user()->id;
        $veh_component->vehicle_name = $this->newveh_name;
        $veh_component->model = $this->newveh_model;
        $veh_component->type = $this->newveh_type;
        $veh_component->distance = $this->newveh_distance;
        $veh_component->mainteance = $this->newveh_alert;
        $veh_component->save();
        return redirect('/dashboard');
    }
}

resources/views/impact/account/components/about.blade.php
<div>
    {{-- Nothing in the world is as soft and yielding as water. --}}
</div>

resources/views/impact/account/components/advancedsettings.blade.php
<div>
    {{-- A good traveler has no fixed plans and is not intent upon arriving. --}}
</div>

resources/views/impact/account/components/connectedevices.blade.php
<div>
    {{-- Success is as dangerous as failure. --}}
</div>

resources/views/impact/account/components/connections.blade.php
<div>
   <div class="card" style="border-radius: 25px;">
      <div class="card-body">
         <center>
            <h2 class="text-primary" style="margin-top:5px;color: #e8253b;"><i class="fad fa-plug"></i></h2>
            <p style="padding:0px;margin:0px;"><strong>Connections</strong></p>
         </center>
      </div>
   </div>
   <br>
   <div class="card" style="border-radius: 25px;">
      <div class="card-body">
         <strong><i class="fab fa-discord"></i> {{ __('Discord') }}</strong>
         <hr>
         When you link your discord to your account you get access to special features and ability to login with your discord account! You'll also get access to our discord server!<br>
         <br>


         @if ($discord_connection)
         <strong>{{ __('You have linked your discord') }}</strong>
         <br><br>

        <img src="https://cdn.discordapp.com/avatars/{{$discord_connection->discord_id}}/{{$discord_connection->avatar}}.jpg" alt="userprofile" class="img-responsive rounded-circle" style="width:75px;height:75px;">
        <strong style="margin-left:10px;">{{$discord_connection->discord_username}}#{{$discord_connection->discord_tag}}</strong>
         @else
         <strong>{{ __('You have not linked your discord') }}</strong>
         <br><br>
         @endif

         @if ($discord_connection)
         <form wire:submit.prevent="destroydc()">
            <button type="submit" class="btn btn-danger float-right" style="border-radius: 25px;">Unlink Discord</button>
         </form>
         @else
            <a href="https://discord.com/api/oauth2/authorize?client_id=764847614825988116&redirect_uri=https%3A%2F%2Fimpactatv.com%2Fdiscorddata&response_type=code&scope=identify%20email" class="btn btn-primary float-right" style="border-radius: 25px;">Link Discord</a>
         @endif
      </div>
   </div>
   <br>
   <!--<div class="card">
      <div class="card-body">
         <strong><i class="fab fa-google"></i> {{ __('Google') }}</strong>
         <hr>
         Link your google account to gain access to login with your google account upon login.<br>
         <br>


         @if (Auth::user()->two_factor_secret)
         @else
         <strong>{{ __('You have not linked your google') }}</strong>
         @endif
         <br><br>


         @if (Auth::user()->two_factor_secret)
         <form wire:submit.prevent="destroydc()">
            <button type="submit" class="btn btn-danger float-right">Unlink Discord</button>
         </form>
         @else
         <form wire:submit.prevent="destroydc()">
            <button type="submit" class="btn btn-primary float-right" disabled>Link Google (Unavailable)</button>
         </form>
         @endif
      </div>
   </div>
   <br>
   <div class="card">
      <div class="card-body">
         <strong><i class="fab fa-facebook"></i> {{ __('Facebook') }}</strong>
         <hr>
         Link your facebook account to gain access to login with your facebook account upon login.<br>
         <br>


         @if (Auth::user()->two_factor_secret)
         @else
         <strong>{{ __('You have not linked your facebook') }}</strong>
         @endif
         <br><br>


         @if (Auth::user()->two_factor_secret)
         <form wire:submit.prevent="destroydc()">
            <button type="submit" class="btn btn-danger float-right">Unlink Discord</button>
         </form>
         @else
         <form wire:submit.prevent="destroydc()">
            <button type="submit" class="btn btn-primary float-right" disabled>Link Facebook (Unavailable)</button>
         </form>
         @endif
      </div>
   </div>
   <br>-->
</div>

resources/views/impact/account/components/general.blade.php
<div>
<div class="card" style="border-radius:25px;">
            <div class="card-body">
               <center>
                  <h2 class="text-primary" style="margin-top:5px;color: #e8253b;"><i class="fad fa-cog"></i></h2>
                  <p style="padding:0px;margin:0px;"><strong>General Settings</strong></p>
               </center>
            </div>
         </div>
         <br>
<div class="card" style="border-radius:25px;">
            <div class="card-body">
            <strong><i class="far fa-cog"></i> {{ __('Profile Information') }}</strong>
<hr>
{{ __('Update your account\'s profile information and email address.') }}
<br><br>
            @if($status == "success")
               <p class="text-success">
                           <i class="fad fa-check-circle"></i> Saved!
               </p>
               @endif

            <form wire:submit.prevent="updateprofileinformation">
            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">Name</label>
               <input type="text" class="form-control" wire:model="name" >
            </div>

            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">Tag</label>
               <input type="text" class="form-control" wire:model="tag" value="{{Auth::user()->tag}}" >
            </div>

            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">Email address</label>
               <input type="email" class="form-control" wire:model="email" value="{{Auth::user()->email}}" >
               <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
               @if(!Auth::user()->email_verified_at)
               <p class="text-danger">
                           <i class="fad fa-times-hexagon"></i> This email has not been verified!
               </p>
               @endif
            </div>

            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">Favorite Trail</label>
               <input type="text" class="form-control" wire:model="fav_trail" value="{{Auth::user()->fav_trail}}" >
            </div>

            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">Favorite Vehicle</label>
               <input type="text" class="form-control" wire:model="fav_vehicle" value="{{Auth::user()->fav_vehicle}}" >
            </div>
               <button type="submit" class="btn btn-primary float-right" style="border-radius:25px;">Save Changes</button><br>
               </form>
            </div>
         </div>
</div>

resources/views/impact/account/components/paymentmethods.blade.php
<div>
    {{-- A good traveler has no fixed plans and is not intent upon arriving. --}}
</div>

resources/views/impact/account/components/privacy.blade.php
<div>
    {{-- The best athlete wants his opponent at his best. --}}
</div>

resources/views/impact/account/components/profilepicture.blade.php
<div>
    <div class="card" style="border-radius: 25px;">
                <div class="card-body">
                   <center>
                      <h2 class="text-primary" style="margin-top:5px;color: #e8253b;"><i class="fad fa-cog"></i></h2>
                      <p style="padding:0px;margin:0px;"><strong>Profile Picture</strong></p>
                   </center>
                </div>
             </div>
             <br>
    <div class="card" style="border-radius: 25px;">
                <div class="card-body">

                   <center>
                    <p class="text-secondary">Current Profile Picture</p>
                    @if(Auth::user()->avatar_url)
                    <div class="user-avatar" style="background-image: url('https://cdn.discordapp.com/avatars/{{$discord_connection->discord_id}}/{{$discord_connection->avatar}}.jpg');width:75px;height:75px;"></div>
                    @else
                    <div class="user-avatar" style="background-image: url('https://www.gravatar.com/avatar/{{ md5( strtolower( trim( Auth::user()->email ) ) )}}&s=100');width:75px;height:75px;"></div>
                    @endif
                    <br>

                    @if(!Auth::user()->avatar_url)
                       <p>Avatar is provided by Gravatar.</p>
                    @else
                        <p>Avatar is provided by Discord.</p>
                    @endif
                       <a href="https://en.gravatar.com/" class="btn btn-sm btn-primary" style="border-radius: 25px;">Set Gravatar</a>

                       @if(Auth::user()->avatar_url)
                       <button wire:click="remove_discord" type="button" style="border-radius: 25px;" class="btn btn-sm btn-danger" @if(!$discord_connection) disabled @endif >Remove Discord Avatar</button>
                       @else
                       <button wire:click="add_discord" type="button" style="border-radius: 25px;" class="btn btn-sm btn-primary" @if(!$discord_connection) disabled @endif >Set Discord Avatar</button>
                       @endif
                    <br><br>
                    </center>
                </div>
             </div>
    </div>

resources/views/impact/account/components/security-pass.blade.php
<div>
<div class="card" style="border-radius: 25px;">
            <div class="card-body">
               <center>
                  <h2 class="text-primary" style="margin-top:5px;color: #e8253b;"><i class="fad fa-fingerprint"></i></h2>
                  <p style="padding:0px;margin:0px;"><strong>Security & Authentication</strong></p>
               </center>
            </div>
         </div>
         <br>
         <div class="card" style="border-radius: 25px;">
            <div class="card-body">
            <form wire:submit.prevent="updatepassword">
            <strong><i class="far fa-lock-alt"></i> {{ __('Update Password') }}</strong>
<hr>
{{ __('Ensure your account is using a long, random password to stay secure.') }}
<br><br>
@if($status == "success")
               <p class="text-success">
                           <i class="fad fa-check-circle"></i> Updated Succesfully!
               </p>
            @elseif($status == "fail")
               <p class="text-danger">
                           <i class="fad fa-times-circle"></i> The current password or new password did not match.
               </p>
            @else
            @endif
            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">Current Password</label>
               <input type="password" class="form-control" wire:model="oldpassword" >
            </div>

            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">New Password</label>
               <input type="password" class="form-control" wire:model="newpassword" >
            </div>

            <div class="mb-3">
               <label for="exampleInputEmail1" class="form-label">Confirm Password</label>
               <input type="password" class="form-control" wire:model="confirmpassword" >
            </div>

            <button type="submit" class="btn btn-primary float-right" style="border-radius: 25px;">Save Changes</button><br>
            </form>
            </div>
         </div>
</div>
<br>

resources/views/impact/account/components/security.blade.php
<div>
<livewire:account.securitypassword/><br>
         <div class="card" style="border-radius: 25px;">
            <div class="card-body">
            <strong><i class="fal fa-mobile-alt"></i> {{ __('Two Factor Authentication') }}</strong>
<hr>
{{ __('Add additional security to your account using two factor authentication.') }}<br>
{{ __('When two factor authentication is enabled, you will be prompted for a secure, random token during authentication. You may retrieve this token from your phone\'s Google Authenticator application.') }}<br>
<br>

@if (Auth::user()->two_factor_secret)
<!--<strong>{{ __('You have enabled two factor authentication.') }}</strong>-->
<div class="row">
        <div class="col-sm-6">
        <strong style="font-size:22px;">{{ __('QR Code & Auth Code') }}</strong><br>
        <img src="data:image/png;base64,{!! $render !!}" alt="userprofile" class="img-responsive" style="width:150px;margin-top:15px;">
        <hr>
        <div>Auth Key : {{ decrypt(Auth::user()->two_factor_secret) }}</div>
        </div>
        <div class="col-sm-6">
        <strong style="font-size:22px;">{{ __('Recovery Codes') }}</strong>
        <div style="margin-top:15px;">
        @foreach (json_decode(decrypt(Auth::user()->two_factor_recovery_codes), true) as $code)
                        <div>{{ $code }}</div>
        @endforeach
        </div>
        </div>
</div>



@else
<strong>{{ __('You have not enabled two factor authentication.') }}</strong>
@endif

<br><br>
@if (Auth::user()->two_factor_secret)
<form wire:submit.prevent="submit(true)">
<button type="submit" class="btn btn-danger float-right" style="border-radius: 25px;">Disable Two Factor Authentication</button>
</form>
@else
<form wire:submit.prevent="submit(false)">
<button type="submit" class="btn btn-primary float-right" style="border-radius: 25px;">Enable Two Factor Authentication</button>
</form>
@endif


            </div>
         </div>

         <br>
</div>